<?php
session_start();

if (!isset($_SESSION['username']) || $_SESSION['username'] === 'Guest') {
    // ÜRES VÁLASZ - SEMMIT SEM KÜLDÜNK VISSZA
    echo '';
    exit;
}
?>
<div class="page-header">
    <h2>🗄️ Database Management</h2>
    <div class="info-box">
        ℹ️ Manage web authentication passwords
    </div>
</div>
 
<!-- Statisztikák -->
<div class="stats-grid">
    <div class="stat-card">
        <div class="stat-icon">✅</div>
        <div class="stat-content">
            <h3>Active Passwords</h3>
            <div id="activePasswords" class="stat-value">-</div>
        </div>
    </div>
    
    <div class="stat-card">
        <div class="stat-icon">❌</div>
        <div class="stat-content">
            <h3>Expired Passwords</h3>
            <div id="expiredPasswords" class="stat-value">-</div>
        </div>
    </div>
    
    <div class="stat-card">
        <div class="stat-icon">📊</div>
        <div class="stat-content">
            <h3>Total Uses</h3>
            <div id="totalUses" class="stat-value">-</div>
        </div>
    </div>
    
    <div class="stat-card">
        <div class="stat-icon">📈</div>
        <div class="stat-content">
            <h3>Average Uses</h3>
            <div id="avgUses" class="stat-value">-</div>
        </div>
    </div>
</div>

<!-- Vezérlők -->
<div class="filters">
    <input type="text" id="passwordSearch" placeholder="🔍 Search users..." class="search-input">
    
    <select id="statusFilter" class="filter-select">
        <option value="">All Status</option>
        <option value="active">Active</option>
        <option value="expired">Expired</option>
        <option value="expired_24h">Expired ≤ 24h</option>
        <option value="expired_old">Expired > 24h</option>
    </select>
    
    <button class="btn btn-secondary" onclick="refreshDatabase()">🔄 Refresh</button>
    <button class="btn btn-primary" onclick="showGeneratePasswordModal()">🔑 Generate Password</button>
    <button class="btn btn-warning" onclick="exportDatabase()">📤 Export CSV</button>
    <button class="btn btn-danger" onclick="cleanupExpired()">🧹 Cleanup Expired</button>
    <button class="btn btn-danger" onclick="deleteOldExpired()" style="display: none;" id="deleteOldBtn">⚠️ Delete Old (>24h)</button>
</div>

<!-- Jelszavak táblázat -->
<div class="table-container">
    <table id="passwordsTable" class="data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>👤 Username</th>
                <th>🔑 Password</th>
                <th>⏰ Expires At</th>
                <th>⏱️ Time Left</th>
                <th>📊 Uses</th>
                <th>👨‍💻 Generated By</th>
                <th>🕒 Created At</th>
                <th>📊 Status</th>
                <th>⚡ Actions</th>
            </tr>
        </thead>
        <tbody id="passwordsTableBody">
            <tr>
                <td colspan="10" style="text-align: center; color: #666;">Loading passwords...</td>
            </tr>
        </tbody>
    </table>
</div>

<!-- Információs doboz -->
<div class="dashboard-section">
    <h3>ℹ️ Database Information</h3>
    <div class="database-info">
        <p><strong>Active Web Passwords:</strong> View and manage all web authentication passwords.</p>
        
        <div class="info-grid">
            <div class="info-item">
                <strong>⚡ Quick Actions:</strong>
                <ul class="features-list">
                    <li><button class="btn-sm btn-primary" onclick="showGeneratePasswordModal()">Generate New Password</button></li>
                    <li><button class="btn-sm btn-warning" onclick="cleanupExpired()">Cleanup Expired</button></li>
                    <li><button class="btn-sm btn-info" onclick="refreshDatabase()">Refresh List</button></li>
                </ul>
            </div>
            
            <div class="info-item">
                <strong>📊 Statistics:</strong>
                <ul class="features-list">
                    <li>Passwords valid for 60 minutes by default</li>
                    <li>Each password can be used 10 times</li>
                    <li>Automatic cleanup of old passwords</li>
                    <li>Real-time usage tracking</li>
                </ul>
            </div>
        </div>
        
        <p><strong>💡 Tip:</strong> You can also generate passwords via IRC using <code>!web</code> command.</p>
    </div>
</div>

<!-- Generate Password Modal -->
<div id="generatePasswordModal" class="modal">
    <div class="modal-content">
        <span class="close" onclick="closeGeneratePasswordModal()">&times;</span>
        <h2>🔑 Generate Web Password</h2>
        
        <form id="generatePasswordForm">
            <div class="form-group">
                <label for="genUsername">Username:</label>
                <input type="text" id="genUsername" name="username" required placeholder="Enter username">
                <small class="form-text">The IRC nickname for authentication</small>
            </div>
            
<div class="form-group">
    <label for="genExpiresIn">Expires In:</label>
    <select id="genExpiresIn" name="expires_in" required>
        <!-- ✅ Rövid időszakok -->
        <option value="10">10 minutes</option>
        <option value="30" selected>30 minutes</option>
        <option value="60">1 hour</option>
        <option value="120">2 hours</option>
        <option value="180">3 hours</option>
        
        <!-- ✅ Közepes időszakok -->
        <option value="360">6 hours</option>
        <option value="720">12 hours</option>
        <option value="1440">24 hours (1 day)</option>
        
        <!-- ✅ Hosszú időszakok -->
        <option value="2880">2 days</option>
        <option value="4320">3 days</option>
        <option value="10080">1 week (7 days)</option>
        <option value="20160">2 weeks</option>
        <option value="30240">3 weeks</option>
        <option value="43200">1 month (30 days)</option>
        
        <!-- ✅ Nagyon hosszú időszakok -->
        <option value="86400">2 months</option>
        <option value="129600">3 months</option>
        <option value="259200">6 months</option>
        <option value="525600">1 year</option>
        
        <!-- ✅ Speciális -->
        <option value="0">Never expires</option>
    </select>
    <small class="form-text">Password validity period (⚠️ "Never expires" should be used with caution!)</small>
</div>
            
			<div class="form-group">
				<label for="genMaxUses">Max Uses:</label>
				<select id="genMaxUses" name="max_uses">
					<option value="10">10 uses</option>
					<option value="50">50 uses</option>
					<option value="100">100 uses</option>
					<!-- ✅ Unlimited hozzáadva -->
					<option value="0">Unlimited (0)</option>
				</select>
				<small class="form-text">Maximum number of logins allowed (0 = unlimited)</small>
			</div>					
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Generate Password</button>
                <button type="button" class="btn btn-secondary" onclick="closeGeneratePasswordModal()">Cancel</button>
            </div>
        </form>
        
        <div id="generatedPasswordResult" style="display: none; margin-top: 20px; padding: 15px; background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 8px;">
            <h3 style="color: #155724; margin-bottom: 10px;">✅ Password Generated!</h3>
            <div class="result-grid">
                <div class="result-item">
                    <strong>Username:</strong> <span id="resultUsername"></span>
                </div>
                <div class="result-item">
                    <strong>Password:</strong> <code id="resultPassword" style="font-size: 1.2rem; font-weight: bold; color: #155724; padding: 5px 10px; background: #fff; border: 1px dashed #28a745; border-radius: 4px;"></code>
                </div>
                <div class="result-item">
                    <strong>Expires in:</strong> <span id="resultExpires"></span> minutes
                </div>
                <div class="result-item">
                    <strong>Max uses:</strong> <span id="resultMaxUses"></span> times
                </div>
                <div class="result-item">
                    <strong>Expires at:</strong> <span id="resultExpiresAt"></span>
                </div>
            </div>
            
            <div style="margin-top: 15px; display: flex; gap: 10px;">
                <button class="btn btn-success" onclick="copyPassword()">📋 Copy Password</button>
                <button class="btn btn-info" onclick="copyAllInfo()">📋 Copy All Info</button>
                <button class="btn btn-secondary" onclick="closeGeneratePasswordModal()">Close</button>
            </div>
        </div>
    </div>
</div>